### ISSUE TITLE
AttributeError: 'ReverseForeignRelation' object has no attribute 'db_table'

### ISSUE THREAD

**Issue by timur-orudzhov** [theatlantic/django-cropduster#35] opened 2015-03-31 07:40 UTC
I get this  message, when applying migrations. Any suggestions how to fix this error ? Thanks in advance.

### Traceback

Traceback (most recent call last):
- File "./manage.py", line 10, in <module>
  - execute_from_command_line(sys.argv)
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
  - utility.execute()
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
  - self.fetch_command(subcommand).run_from_argv(self.argv)
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
  - self.execute(*args, **options.__dict__)
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
  - output = self.handle(*args, **options)
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 154, in handle
  - ProjectState.from_apps(apps),
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 108, in from_apps
  - model_state = ModelState.from_model(model)
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 190, in from_model
  - name, path, args, kwargs = field.deconstruct()
- File "/home/timur/.virtualenvs/e-travel/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 2110, in deconstruct
  if self.db_table is not None:

##### AttributeError: 'ReverseForeignRelation' object has no attribute 'db_table'

**Comment by fdintino** [comment] 2015-03-31 12:12
It looks like you are using Django 1.8. django-cropduster does not yet support Django 1.8, and I'm afraid we won't even begin adding support until after it gets out of release candidate status. If it's an option, my suggestion is to use Django 1.7 until Django 1.8 support is broader (The final version is scheduled to be released tomorrow), since ours isn't the only project that waits for Django release to become final before beginning development against it.

**Comment by timur-orudzhov** [comment] 2015-03-31 12:59
fdintino, thanks. but i'm using 1.7.6 version of django.

**Comment by fdintino** [comment] 2015-03-31 16:01
Oh! Sorry about that, I didn't realize they backported `Field.deconstruct()` to 1.7. I'll take a look at this later in the week.

**Comment by fdintino** [comment] 2015-05-29 01:52
Could you see if this is fixed with the changes I just pushed out?

**Comment by fdintino** [comment] 2015-06-01 15:35
I was able to reproduce your error, and it is not field by the latest changes. I'm testing a branch that would fix migrations and will soon merge it into master.

**Comment by fdintino** [comment] 2015-06-05 17:44
@timur-orudzhov This has been fixed and merged in. Sorry for the delay in getting this taken care of. Open another ticket if you have any further issues.

Thanks for the report!

**Closed by fdintino** 2015-06-05 17:44 UTC
